import streamlit as st
import pandas as pd
import numpy as np
import joblib

import os

print("Current folder:", os.getcwd())
print("Files here:", os.listdir())
# -----------------------------
# PAGE
# -----------------------------

st.set_page_config(page_title="DriveValue AI", page_icon="🚗")

st.title("🚗 DriveValue AI")

st.markdown("""
### Explainable Used Car Price Prediction System

Predict the estimated asking price of a used vehicle using a Machine Learning model trained on historical vehicle listings.

**Built with:**
- Python
- Scikit-learn
- Random Forest Regression
- Streamlit
- CRISP-DM Methodology
""")

st.info("""
**Disclaimer**

Predicted prices are estimates generated by a machine learning model and should be used as guidance only. They are not official vehicle valuations.
""")
st.write("Predict the asking price of a used vehicle.")

# -----------------------------
# LOAD MODEL
# -----------------------------

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

model = joblib.load(BASE_DIR / "models" / "random_forest_model.pkl")
feature_columns = joblib.load(BASE_DIR / "models" / "feature_columns.pkl")

# -----------------------------
# LOAD RAW DATA
# -----------------------------

df = pd.read_csv(BASE_DIR / "Data" / "processed" / "used_cars_cleaned.csv")

# -----------------------------
# DROPDOWNS
# -----------------------------

# ----------------------------
# LOAD OPTIONS FROM TRAINING DATA
# ----------------------------

brands = sorted([
    c.replace("Brand_", "")
    for c in feature_columns
    if c.startswith("Brand_")
])

models = sorted([
    c.replace("model_", "")
    for c in feature_columns
    if c.startswith("model_")
])

fuel_types = sorted([
    c.replace("FuelType_", "")
    for c in feature_columns
    if c.startswith("FuelType_")
])

transmissions = sorted([
    c.replace("Transmission_", "")
    for c in feature_columns
    if c.startswith("Transmission_")
])

owners = sorted([
    c.replace("Owner_", "")
    for c in feature_columns
    if c.startswith("Owner_")
])

posted_dates = sorted([
    c.replace("PostedDate_", "")
    for c in feature_columns
    if c.startswith("PostedDate_")
])
# -----------------------------
# USER INPUT
# -----------------------------

col1, col2 = st.columns(2)

with col1:

    year = st.number_input(
        "Year",
        1990,
        2026,
        2018
    )

    # Calculate age automatically
    CURRENT_YEAR = 2024
    age = CURRENT_YEAR - year

    km = st.number_input(
        "Kilometres Driven",
        0,
        500000,
        65000
    )

    brand = st.selectbox(
        "Brand",
        brands
    )

    model_name = st.selectbox(
        "Model",
        models
    )

with col2:

    fuel = st.selectbox(
        "Fuel Type",
        fuel_types
    )

    transmission = st.selectbox(
        "Transmission",
        transmissions
    )

    owner = st.selectbox(
        "Owner",
        owners
    )

    posted = st.selectbox(
        "Posted Date",
        posted_dates
    )
# -----------------------------
# CREATE INPUT
# -----------------------------

input_df = pd.DataFrame(
    np.zeros((1, len(feature_columns))),
    columns=feature_columns
)

input_df["Year"] = year
input_df["Age"] = age
input_df["kmDriven"] = km

# Brand
col = f"Brand_{brand}"
if col in input_df.columns:
    input_df[col] = 1

# Model
col = f"model_{model_name}"
if col in input_df.columns:
    input_df[col] = 1

# Fuel
col = f"FuelType_{fuel}"
if col in input_df.columns:
    input_df[col] = 1

# Owner
col = f"Owner_{owner}"
if col in input_df.columns:
    input_df[col] = 1

# Transmission
col = f"Transmission_{transmission}"
if col in input_df.columns:
    input_df[col] = 1

# Posted Date
col = f"PostedDate_{posted}"
if col in input_df.columns:
    input_df[col] = 1

# -----------------------------
# PREDICTION
# -----------------------------

if st.button("Predict Vehicle Price"):

    vehicle = pd.DataFrame(
        np.zeros((1, len(feature_columns))),
        columns=feature_columns
    )

    vehicle.loc[0, "Year"] = year
    vehicle.loc[0, "Age"] = age
    vehicle.loc[0, "kmDriven"] = km

    mappings = {
        "Brand": brand,
        "model": model_name,
        "FuelType": fuel,
        "Transmission": transmission,
        "Owner": owner,
        "PostedDate": posted
    }

    for prefix, value in mappings.items():
        column = f"{prefix}_{value}"
        if column in vehicle.columns:
            vehicle.loc[0, column] = 1

    vehicle = vehicle[feature_columns]

    prediction = model.predict(vehicle)[0]

    st.success("Prediction generated successfully!")

    st.metric(
        label="Estimated Asking Price",
        value=f"₹ {prediction:,.0f}"
    )

    st.caption(
        "This value is an estimate generated by the trained Random Forest Regression model."
    )